version: "3.7"
services:
  db:
    container_name: db
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
      args:
        name: weather
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
